#This GitHub Actions CI pipeline ensures code quality, security, and testing for a Python project. It runs on push to main and pull requests, using Python 3.9. 
#The workflow installs dependencies, performs Flake8 linting for code style, Bandit scanning for security issues, and Pytest for unit tests, generating reports. 
#Finally, it uploads all reports as artifacts for debugging, ensuring clean, secure, and well-tested code before merging.




name: Python CI Pipeline

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install pytest pytest-html pytest-cov flake8 bandit

      - name: Run Linting (Flake8)
        run: flake8 --output-file=flake8_report.txt || true

      - name: Run Security Scan (Bandit)
        run: bandit -r . -o bandit_report.txt || true

      - name: Run Tests & Generate HTML Report
        run: pytest --cov=app --cov-report=term --cov-report=html --html=pytest_report.html --self-contained-html || true

      - name: Check htmlcov contents
        run: ls -l htmlcov

      - name: Debug workspace
        run: ls -R

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: |
            pytest_report.html
            flake8_report.txt
            bandit_report.txt
            htmlcov/
